# Generated by Django 6.0 on 2026-01-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_futsal_court_futsal'),
    ]

    operations = [
        migrations.AddField(
            model_name='futsal',
            name='map_link',
            field=models.URLField(blank=True, help_text='Google Maps link for the venue location'),
        ),
    ]
