# Generated by Django 6.0 on 2025-12-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('futsal_owner', 'Futsal Owner'), ('admin', 'Administrator')], default='player', max_length=20),
        ),
    ]
